### ISSUE TITLE
Cannot Load Dataset

### ISSUE THREAD

**Issue by jawadSajid** [databrickslabs/dolly#160]
Hi,

I have my instruction dataset with such samples in a file named "databricks-dolly-15k".

```
{"instruction": "Paraphrase the following text.", "context": "Hi loremipsum,\nDo you work there? I need you to set up an outgoing Internet wire for me right away.", "response": "Hey loremipsum,\nAre you employed at that location? I require your assistance in arranging an immediate outgoing access to the internet for me.", "category": "paraphrase"}
```

I cannot load it from trainer.py, cannot figure out why.

Trackback is a follows:
```
Traceback (most recent call last):
  File "trainer.py", line 334, in <module>
    main()
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "trainer.py", line 326, in main
    train(**kwargs)
  File "trainer.py", line 227, in train
    processed_dataset = preprocess_dataset(tokenizer=tokenizer, max_length=max_length, seed=seed, training_dataset=training_dataset)
  File "trainer.py", line 159, in preprocess_dataset
    dataset = load_training_dataset(training_dataset)
  File "trainer.py", line 90, in load_training_dataset
    dataset = load_dataset(path_or_dataset)
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/datasets/load.py", line 1773, in load_dataset
    builder_instance = load_dataset_builder(
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/datasets/load.py", line 1502, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/mnt/dsc-nfs-1/jawad-sajid/DOLLY/dolly-env/lib/python3.8/site-packages/datasets/load.py", line 1221, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /mnt/dsc-nfs-1/jawad-sajid/DOLLY/dataset/databricks-dolly-15k/databricks-dolly-15k.py or any data file in the same directory.

```
Python 3.8.10 pip freeze as follows:
```
accelerate==0.19.0
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
cmake==3.26.3
datasets==2.12.0
dill==0.3.6
filelock==3.12.0
frozenlist==1.3.3
fsspec==2023.5.0
huggingface-hub==0.14.1
idna==3.4
Jinja2==3.1.2
lit==16.0.3
MarkupSafe==2.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.0.1
psutil==5.9.5
pyarrow==12.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.30.0
responses==0.18.0
six==1.16.0
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
tqdm==4.65.0
transformers==4.29.1
triton==2.0.0
typing-extensions==4.5.0
tzdata==2023.3
urllib3==2.0.2
xxhash==3.2.0
yarl==1.9.2
```

**Comment by srowen** [comment]
You need to pass a named dataset, or path, that `datasets` can load with `load_dataset`. It should work if you point at a ".jsonl" file path. I am not sure what you have here though, and it's saying it can't load, so try debugging that directly first. This isn't related to this code or model. See what works here: https://huggingface.co/datasets/databricks/databricks-dolly-15k/tree/main

**Comment by jawadSajid** [comment]
Thanks, works.
There was an error in my dataset structure.
