### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'load_in_8bit'

### ISSUE THREAD

**Issue by chintan-donda** [databrickslabs/dolly#168]
Getting below issue when running with load_in_8bit:
`TypeError: __init__() got an unexpected keyword argument 'load_in_8bit'`

My Env details:
Running the model in Amazon SageMaker Notebook Instances.
```
CUDA Version: 11.7
Python version: 3.9
bitsandbytes-cuda117
```

Let me know if any other details are required.

**Comment by srowen** [comment]
Please show the line of code where you set this

**Comment by chintan-donda** [comment]
@srowen I've set it in training.trainer.py

```
def load_model(
    pretrained_model_name_or_path: str = DEFAULT_INPUT_MODEL, *, gradient_checkpointing: bool = False
) -> AutoModelForCausalLM:
    logger.info(f"Loading model for {pretrained_model_name_or_path}")
    model = AutoModelForCausalLM.from_pretrained(
        pretrained_model_name_or_path, trust_remote_code=True, use_cache=False if gradient_checkpointing else True,
        **load_in_8bit=True, device_map='auto'**
    )
    return model
```

**Comment by chintan-donda** [comment]
I'm using it as I want to train the model with limited GPU memory of 16 GB.
Any suggestion, how can I train the model `EleutherAI/pythia-2.8b` on 16 GB memory GPU?
FYI, I've already tried reducing batch size = 3. But that's giving OOM error.

**Comment by srowen** [comment]
Reduce batch size to 1. You may have longer inputs

**Comment by srowen** [comment]
Try param offload - this really isn't specific to this model but to your data and deepspeed settings

**Comment by chintan-donda** [comment]
With below settings inside `"zero_optimization"` section in `ds_z3_bf16_config.json`?
```
"offload_optimizer": {
  "device": "cpu",
  "pin_memory": true
},
```
and NOT using (commenting out) `# load_in_8bit=True, device_map='auto'`

with above setup, getting new issue now:
```
2023-05-16 19:27:44 INFO [torch.distributed.distributed_c10d] Added key: store_based_barrier_key:2 to store for rank: 0
2023-05-16 19:27:44 INFO [torch.distributed.distributed_c10d] Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
 [WARNING]  cpu_adam cuda is missing or is incompatible with installed torch, only cpu ops can be compiled!
Using /home/users/abc/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Creating extension directory /home/users/abc/.cache/torch_extensions/py38_cu118/cpu_adam...
Emitting ninja build file /home/users/abc/.cache/torch_extensions/py38_cu118/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/TH -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -march=native -fopenmp -D__AVX256__ -D__DISABLE_CUDA__ -c /home/users/abc/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o 
[2/2] c++ cpu_adam.o -shared -fopenmp -L/home/users/abc/venv/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o cpu_adam.so
Loading extension module cpu_adam...
Time to load cpu_adam op: 75.48912215232849 seconds
Using /home/users/abc/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Creating extension directory /home/users/abc/.cache/torch_extensions/py38_cu118/utils...
Emitting ninja build file /home/users/abc/.cache/torch_extensions/py38_cu118/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/TH -isystem /home/users/abc/venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /home/users/abc/venv/lib/python3.8/site-packages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o 
[2/2] c++ flatten_unflatten.o -shared -L/home/users/abc/venv/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o utils.so
Loading extension module utils...
Time to load utils op: 26.54496741294861 seconds
Parameter Offload: Total persistent parameters: 1070080 in 258 params
2023-05-16 19:29:44 ERROR [__main__] main failed
Traceback (most recent call last):
  File "/home/users/abc/dolly/training/trainer.py", line 334, in <module>
    main()
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/abc/dolly/training/trainer.py", line 326, in main
    train(**kwargs)
  File "/home/users/abc/dolly/training/trainer.py", line 281, in train
    trainer.train()
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1741, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1463, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 600, in _create_fp16_partitions_with_defragmentation
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 436, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/abc/dolly/training/trainer.py", line 334, in <module>
    main()
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/abc/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/abc/dolly/training/trainer.py", line 326, in main
    train(**kwargs)
  File "/home/users/abc/dolly/training/trainer.py", line 281, in train
    trainer.train()
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1741, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/users/abc/venv/lib/python3.8/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1463, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 600, in _create_fp16_partitions_with_defragmentation
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/users/abc/venv/lib/python3.8/site-packages/deepspeed/runtime/zero/stage3.py", line 436, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
[2023-05-16 19:29:48,876] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 76847
[2023-05-16 19:29:48,876] [ERROR] [launch.py:434:sigkill_handler] ['/home/users/abc/venv/bin/python3.8', '-u', '-m', 'training.trainer', '--local_rank=0', '--deepspeed', '/home/users/abc/dolly/config/ds_z3_bf16_config.json', '--epochs', '1', '--local-output-dir', './dolly_2023-05-16_19-26-31', '--dbfs-output-dir', '', '--per-device-train-batch-size', '3', '--per-device-eval-batch-size', '3', '--lr', '1e-5', '--warmup-steps', '50', '--input-model', 'EleutherAI/pythia-2.8b', '--logging-steps', '1000', '--test-size', '10'] exits with return code = 1
```

**Comment by chintan-donda** [comment]
@srowen Downgraded deepspeed to `pip install deepspeed==0.8.3`.

Now new issue:
```
Exception: >- DeepSpeed Op Builder: Installed CUDA version 9.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/chintan/dolly/training/trainer.py", line 334, in <module>
    main()
  File "/home/users/chintan/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/chintan/dolly/training/trainer.py", line 326, in main
    train(**kwargs)
  File "/home/users/chintan/dolly/training/trainer.py", line 281, in train
    trainer.train()
  File "/home/users/chintan/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1664, in train
    return inner_training_loop(
  File "/home/users/chintan/venv/lib/python3.8/site-packages/transformers/trainer.py", line 1741, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/users/chintan/venv/lib/python3.8/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1354, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 96, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 500, in jit_load
    self.build_for_cpu = not assert_no_cuda_mismatch(self.name)
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 105, in assert_no_cuda_mismatch
    raise Exception(
Exception: >- DeepSpeed Op Builder: Installed CUDA version 9.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f4a40638b80>
Traceback (most recent call last):
  File "/home/users/chintan/venv/lib/python3.8/site-packages/deepspeed/ops/adam/cpu_adam.py", line 110, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
```

**Comment by srowen** [comment]
I'm guessing you did not install the NVIDIA libs showing in the script

**Comment by chintan-donda** [comment]
@srowen any specific libs? That would help me fix the issue quickly.

**Comment by chintan-donda** [comment]
@srowen Already did all of the below installations:
```
# MAGIC %md
# MAGIC Install these additional NVIDIA libraries for Databricks Runtime 12.2 ML:

# COMMAND ----------

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb -O /tmp/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb && \
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcublas-dev-11-3_11.5.1.109-1_amd64.deb -O /tmp/libcublas-dev-11-3_11.5.1.109-1_amd64.deb && \
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb -O /tmp/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb && \
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/libcurand-dev-11-3_10.2.4.109-1_amd64.deb -O /tmp/libcurand-dev-11-3_10.2.4.109-1_amd64.deb && \
dpkg -i /tmp/libcusparse-dev-11-3_11.5.0.58-1_amd64.deb && \
dpkg -i /tmp/libcublas-dev-11-3_11.5.1.109-1_amd64.deb && \
dpkg -i /tmp/libcusolver-dev-11-3_11.1.2.109-1_amd64.deb && \
dpkg -i /tmp/libcurand-dev-11-3_10.2.4.109-1_amd64.deb
```

Still the same issue.

**Comment by srowen** [comment]
Oh, it's this, mismatched CUDA versions:
Exception: >- DeepSpeed Op Builder: Installed CUDA version 9.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
You need CUDA 11.x
