### ISSUE TITLE
[HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name']

### ISSUE THREAD

**Issue by Umesh1307** [databrickslabs/dolly#173]
I'm Trying to train

Model Type: EleutherAI/pythia-2.8b 

Error Type: [HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name']

![dolly2_hf](https://github.com/databrickslabs/dolly/assets/75175373/34f2c864-99b8-482c-8ce6-52ef5f425be4)

I Believe this cluster configuration is capable enough to train this model

Compute Detail:
{
    "num_workers": 0,
    "cluster_name": "DollyPOCCluster",
    "spark_version": "12.2.x-gpu-ml-scala2.12",
    "spark_conf": {
        "spark.master": "local[*, 4]",
        "spark.databricks.cluster.profile": "singleNode"
    },
    "aws_attributes": {
        "first_on_demand": 1,
        "availability": "SPOT_WITH_FALLBACK",
        "zone_id": "auto",
        "spot_bid_price_percent": 100,
        "ebs_volume_count": 0
    },
    "node_type_id": "g4dn.2xlarge",
    "driver_node_type_id": "g4dn.2xlarge",
    "ssh_public_keys": [],
    "custom_tags": {
        "ResourceClass": "SingleNode"
    },
    "spark_env_vars": {},
    "autotermination_minutes": 20,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [],
    "enable_local_disk_encryption": false,
    "data_security_mode": "NONE",
    "runtime_engine": "STANDARD",
    "cluster_id": "0517-050920-dmg5higv"
}

RUN LOGS:
[2023-05-17 10:15:28,465] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-05-17 10:15:28,473] [INFO] [runner.py:550:main] cmd = /local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --module --enable_each_rank_log=None training.trainer --input-model EleutherAI/pythia-2.8b --deepspeed /Workspace/Repos/dolly/config/ds_z3_bf16_config.json --epochs 2 --local-output-dir /local_disk0/dolly_training/dolly__2023-05-17T10-15-18 --dbfs-output-dir /dbfs/dolly_training/dolly__2023-05-17T10-15-18 --per-device-train-batch-size 6 --per-device-eval-batch-size 6 --logging-steps 10 --save-steps 200 --save-total-limit 20 --eval-steps 50 --warmup-steps 50 --test-size 200 --lr 5e-6
[2023-05-17 10:15:32,322] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-05-17 10:15:32,323] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-05-17 10:15:32,323] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-05-17 10:15:32,323] [INFO] [launch.py:162:main] dist_world_size=1
[2023-05-17 10:15:32,323] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
2023-05-17 10:15:34.898239: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-17 10:15:35.037391: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-05-17 10:15:43 INFO [__main__] Loading tokenizer for EleutherAI/pythia-2.8b
Downloading (…)okenizer_config.json: 100%|█████| 396/396 [00:00<00:00, 59.8kB/s]
Downloading (…)/main/tokenizer.json: 100%|█| 2.11M/2.11M [00:00<00:00, 6.89MB/s]
Downloading (…)cial_tokens_map.json: 100%|███| 99.0/99.0 [00:00<00:00, 59.9kB/s]
2023-05-17 10:15:45 INFO [__main__] Loading model for EleutherAI/pythia-2.8b
Downloading (…)lve/main/config.json: 100%|██████| 571/571 [00:00<00:00, 339kB/s]
Downloading pytorch_model.bin: 100%|████████| 5.68G/5.68G [00:31<00:00, 182MB/s]
2023-05-17 10:16:48 INFO [__main__] Found max lenth: 2048
2023-05-17 10:16:48 INFO [__main__] Loading dataset from /dbfs/FileStore/tables/clinical_dolly.jsonl
2023-05-17 10:16:49 WARNING [datasets.builder] Found cached dataset json (/root/.cache/huggingface/datasets/json/clinical_dolly.jsonl-764c9aeb7bf7fac0/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 543.51it/s]
2023-05-17 10:16:49 INFO [__main__] Found 26 rows
2023-05-17 10:16:49 INFO [__main__] Preprocessing dataset                       
2023-05-17 10:16:49 INFO [__main__] Processed dataset has 26 rows               
2023-05-17 10:16:49 INFO [__main__] Processed dataset has 26 rows after filtering for truncated records
2023-05-17 10:16:49 INFO [__main__] Shuffling dataset
2023-05-17 10:16:49 INFO [__main__] Done preprocessing
2023-05-17 10:16:49 ERROR [__main__] main failed
Traceback (most recent call last):
  File "/Workspace/Repos/dolly/training/trainer.py", line 329, in <module>
    main()
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Workspace/Repos/dolly/training/trainer.py", line 321, in main
    train(**kwargs)
  File "/Workspace/Repos/dolly/training/trainer.py", line 226, in train
    split_dataset = processed_dataset.train_test_split(test_size=test_size, seed=seed)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/fingerprint.py", line 511, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 4365, in train_test_split
    raise ValueError(
ValueError: test_size=200 should be either positive and smaller than the number of samples 26 or a float in the (0, 1) range
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Workspace/Repos/dolly/training/trainer.py", line 329, in <module>
    main()
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/databricks/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Workspace/Repos/dolly/training/trainer.py", line 321, in main
    train(**kwargs)
  File "/Workspace/Repos/dolly/training/trainer.py", line 226, in train
    split_dataset = processed_dataset.train_test_split(test_size=test_size, seed=seed)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/fingerprint.py", line 511, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 4365, in train_test_split
    raise ValueError(
ValueError: test_size=200 should be either positive and smaller than the number of samples 26 or a float in the (0, 1) range
[2023-05-17 10:16:52,394] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 8886

======================
Another Error

  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-07b069a9-fc74-46da-b629-0e873bf200ec/lib/python3.9/site-packages/transformers/training_args.py", line 1290, in __post_init__
    raise ValueError(
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0
Traceback (most recent call last):

**Comment by srowen** [comment]
Yes, the errors are telling you what the problem is:
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0
Traceback (most recent call last):
You asked for bf16 generation somewhere and are not running on Ampere GPUs. You'd have to change the script for non-Ampere GPUs to use fp16.
