### ISSUE TITLE
Out of Memory in A100 Google Colab Pro+

### ISSUE THREAD

**Issue by jamesjohnson1025** [databrickslabs/dolly#207]
Hello, I was fine-tuning the dolly-15k dataset on Google Colab. Basically running the same code. The modification I made was loading the dataset from Hugging Face and setting the batch size to 1.  I encountered an "Out of Memory" error. Below is the log detailing the issue. I'm using Google Colab Pro+ with a A100 40 GB GPU, 82 GB RAM, and 168 B disk capacity. Is there something crucial that I might be overlooking?

[2023-07-27 02:09:45,934] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-27 02:09:48,593] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-07-27 02:09:48,606] [INFO] [runner.py:555:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --module --enable_each_rank_log=None sample_data.training.trainer --input-model EleutherAI/pythia-6.9b --deepspeed /sample_data/config/a100_config.json --epochs 2 --local-output-dir /sample_data/local_training_root/dolly__1__2023-07-27T01:41:29 --dbfs-output-dir /sample_data/dbfs/dolly_training/dolly__1__2023-07-27T01:41:29 --per-device-train-batch-size 1 --per-device-eval-batch-size 1 --logging-steps 10 --save-steps 200 --save-total-limit 20 --eval-steps 50 --warmup-steps 50 --test-size 200 --lr 5e-6 --bf16 true
[2023-07-27 02:09:50,279] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.15.5-1+cuda11.8
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.15.5-1
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.15.5-1
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.15.5-1+cuda11.8
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-07-27 02:09:52,813] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.15.5-1
[2023-07-27 02:09:52,813] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-07-27 02:09:52,813] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-07-27 02:09:52,813] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-07-27 02:09:52,813] [INFO] [launch.py:163:main] dist_world_size=1
[2023-07-27 02:09:52,813] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
2023-07-27 02:09:55.867406: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2023-07-27 02:09:57,987] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-07-27 02:10:04 INFO [__main__] Loading tokenizer for EleutherAI/pythia-6.9b
2023-07-27 02:10:05 INFO [__main__] Loading model for EleutherAI/pythia-6.9b
Loading checkpoint shards: 100% 2/2 [00:09<00:00,  4.63s/it]
2023-07-27 02:11:14 INFO [__main__] Found max lenth: 2048
2023-07-27 02:11:14 INFO [__main__] Loading dataset from ./sample_data/databricks/databricks-dolly-15k
2023-07-27 02:11:21 INFO [__main__] Found 15011 rows
2023-07-27 02:11:21 INFO [__main__] Preprocessing dataset
2023-07-27 02:11:21 INFO [__main__] Processed dataset has 15011 rows
2023-07-27 02:11:21 INFO [__main__] Processed dataset has 14977 rows after filtering for truncated records
2023-07-27 02:11:21 INFO [__main__] Shuffling dataset
2023-07-27 02:11:21 INFO [__main__] Done preprocessing
2023-07-27 02:11:21 INFO [__main__] Train data size: 14877
2023-07-27 02:11:21 INFO [__main__] Test data size: 100
2023-07-27 02:11:21 INFO [torch.distributed.distributed_c10d] Added key: store_based_barrier_key:1 to store for rank: 0
2023-07-27 02:11:21 INFO [torch.distributed.distributed_c10d] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
2023-07-27 02:11:21 INFO [__main__] Instantiating Trainer
2023-07-27 02:11:29 INFO [__main__] Training
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
2023-07-27 02:11:30 ERROR [__main__] main failed
Traceback (most recent call last):
  File "/content/sample_data/training/trainer.py", line 323, in <module>
    main()
  File "/content/sample_data/training/trainer.py", line 296, in main
    train(
  File "/content/sample_data/training/trainer.py", line 281, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1030, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1340, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 667, in __init__
    self._ddp_init_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 733, in _ddp_init_helper
    self.reducer = dist.Reducer(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 25.54 GiB (GPU 0; 39.56 GiB total capacity; 25.67 GiB already allocated; 12.88 GiB free; 25.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/sample_data/training/trainer.py", line 323, in <module>
    main()
  File "/content/sample_data/training/trainer.py", line 296, in main
    train(
  File "/content/sample_data/training/trainer.py", line 281, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1030, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1340, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 667, in __init__
    self._ddp_init_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 733, in _ddp_init_helper
    self.reducer = dist.Reducer(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 25.54 GiB (GPU 0; 39.56 GiB total capacity; 25.67 GiB already allocated; 12.88 GiB free; 25.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-07-27 02:11:31,918] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 15379
[2023-07-27 02:11:31,918] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', '-m', 'sample_data.training.trainer', '--local_rank=0', '--input-model', 'EleutherAI/pythia-6.9b', '--deepspeed', '/sample_data/config/a100_config.json', '--epochs', '2', '--local-output-dir', '/sample_data/local_training_root/dolly__1__2023-07-27T01:41:29', '--dbfs-output-dir', '/sample_data/dbfs/dolly_training/dolly__1__2023-07-27T01:41:29', '--per-device-train-batch-size', '1', '--per-device-eval-batch-size', '1', '--logging-steps', '10', '--save-steps', '200', '--save-total-limit', '20', '--eval-steps', '50', '--warmup-steps', '50', '--test-size', '200', '--lr', '5e-6', '--bf16', 'true'] exits with return code = 1

**Comment by srowen** [comment]
The default config should work on an A100. My guess is that something else in your session already allocated memory?

**Comment by jamesjohnson1025** [comment]
Hi, Thanks for the response. Below are the steps currently in my jupyter notebook. The only change i have made was using the dataset from hugging face and the rest remains the same. Any idea to figure out where the memory is been allocated. 
Notebook: https://colab.research.google.com/drive/1Tfzyr2LVjhg34jwH-rkp2uPcB3B1kHWN?usp=sharing

```Step 1
!pip3 install deepspeed
!pip install click
!pip install datasets
!pip install "accelerate>=0.16.0,<1" "transformers[torch]>=4.28.1,<5" "torch>=1.13.1,<2"

Step 2
------
import os
import re
from datetime import datetime
from sample_data.training.consts import DEFAULT_INPUT_MODEL, SUGGESTED_INPUT_MODELS
from sample_data.training.trainer import load_training_dataset, load_tokenizer

Step 3
------
timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
model_name = "dolly"

experiment_id = "1"
input_model = DEFAULT_INPUT_MODEL

if experiment_id:
    experiment_id = re.sub(r"\s+", "_", experiment_id.strip())
    model_name = f"{model_name}__{experiment_id}"

checkpoint_dir_name = f"{model_name}__{timestamp}"

dolly_training_dir_name = "dolly_training"

Step 4
--------
# Use the local training root path if it was provided.  Otherwise try to find a sensible default.
local_training_root = "/sample_data/local_training_root"
if not local_training_root:
    # Use preferred path when working in a Databricks cluster if it exists.
    if os.path.exists("/local_disk0"):
        local_training_root = os.path.join("/local_disk0", dolly_training_dir_name)
    # Otherwise use the home directory.
    else:
        local_training_root = os.path.join(os.path.expanduser('~'), dolly_training_dir_name)

Step 5
-------
dbfs_output_root = f"/sample_data/dbfs/{dolly_training_dir_name}"

Step 6
-------
os.makedirs(local_training_root, exist_ok=True)
os.makedirs(dbfs_output_root, exist_ok=True)

Step 7
-------
local_output_dir = os.path.join(local_training_root, checkpoint_dir_name)
dbfs_output_dir = os.path.join(dbfs_output_root, checkpoint_dir_name)
tensorboard_display_dir = f"{local_output_dir}/runs"

Step 8
-------
gpu_family = "a100"
config_file_name = f"{gpu_family}_config.json"
deepspeed_config = os.path.join(os.getcwd(), "/sample_data/config", config_file_name)
print(f"Deepspeed config file: {deepspeed_config}")

Step 9
--------
batch_size = 3
if gpu_family == "a10":
    batch_size = 4
elif gpu_family == "a100":
    batch_size = 6

Step 10
--------
num_gpus_flag = ""
num_gpus = 1
if num_gpus:
    num_gpus = int(num_gpus)
    num_gpus_flag = f"--num_gpus={num_gpus}"

Step 11
---------
if gpu_family == "v100":
    bf16_flag = "--bf16 false"
else:
    bf16_flag = "--bf16 true"

Step 12
--------
os.environ["TOKENIZERS_PARALLELISM"] = "false"

Step 13 
---------
!deepspeed {num_gpus_flag} \
    --module sample_data.training.trainer \
    --input-model {input_model} \
    --deepspeed {deepspeed_config} \
    --epochs 2 \
    --local-output-dir {local_output_dir} \
    --dbfs-output-dir {dbfs_output_dir} \
    --per-device-train-batch-size 1 \
    --per-device-eval-batch-size 1 \
    --logging-steps 10 \
    --save-steps 200 \
    --save-total-limit 20 \
    --eval-steps 50 \
    --warmup-steps 50 \
    --test-size 200 \
    --lr 5e-6 \
    {bf16_flag}

**Comment by srowen** [comment]
If you changed the data set, it's possible you have an input that is too long.
It looks like you changed more though, like even what training code this is pointing to.
Sorry there is just too much that seems to be different here in what you're doing, it's not really possible to debug it all. 
The provided script works as-is, so it's your modifications.
