### ISSUE TITLE
Tensors must be contiguous when deepspeed broadcasting

### ISSUE THREAD

**Issue by wangshanyw** [databrickslabs/dolly#33]
When I train the model with one GPU. It works. But When I set the --num_gpus 8, it returns "Tensors must be contiguous".

The command:
`deepspeed --num_gpus 8  --module training.trainer --deepspeed /root/github/dolly/config/ds_z3_bf16_config.json  --epochs 1 --local-output-dir /root/models/dolly/dolly --per-device-train-batch-size 8 --per-device-eval-batch-size 8 --lr 1e-5`

The output:
`Traceback (most recent call last):
  File "/root/miniconda3/envs/dolly/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None, 

  File "/root/miniconda3/envs/dolly/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)

  File "/root/github/dolly/training/trainer.py", line 265, in <module>
    main()

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)

  File "/root/github/dolly/training/trainer.py", line 257, in main
    train(**kwargs)

  File "/root/github/dolly/training/trainer.py", line 220, in train
    trainer.train()

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/transformers/trainer.py", line 1612, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/transformers/deepspeed.py", line 344, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 301, in __init__
    self._configure_distributed_model(model)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_distributed_model
    self._broadcast_model()

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1102, in _broadcast_model
    dist.broadcast(p,

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 127, in log_wrapper
    return func(*args, **kwargs)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 232, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 70, in broadcast
    return torch.distributed.broadcast(tensor=tensor,

  File "/root/miniconda3/envs/dolly/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1404, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: Tensors must be contiguous`

**Comment by srowen** [comment]
What are you running on? does it have 8 GPUs?

**Comment by wangshanyw** [comment]
![image](https://user-images.githubusercontent.com/63636284/228710822-07e1f953-9d21-4d73-b5f1-7f3c71093f85.png)
I am running it on my own server and it has 8 GPUs. This problem also occurs when the num_gpus set to 1 or 2, or 4.

**Comment by srowen** [comment]
You're on CUDA 12. I wonder if that makes a difference, or if you're following this repo, if you're installing CUDA 11.3 libs. I would think that would result in a different error. No idea why it wouldn't work otherwise

**Comment by wangshanyw** [comment]
Thanks, I'll try it. Hope it works.
