### ISSUE TITLE
Getting error "execution_count": null 

### ISSUE THREAD

**Issue by singhalshikha518** [databrickslabs/dolly#92]
I tried running trainer.py using deep speed and getting below error.
[2023-04-16 18:06:26,041] [WARNING] [runner.py:190:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2,3 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.
[2023-04-16 18:06:26,067] [INFO] [runner.py:540:main] cmd = /home/stsingha/anaconda3/envs/openchatkit_fastapi/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None /home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb --deepspeed --deepspeed_config /home/stsingha/LLM/dolly/training/deepspeedconfig.json
[2023-04-16 18:06:29,624] [INFO] [launch.py:229:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2023-04-16 18:06:29,624] [INFO] [launch.py:235:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-04-16 18:06:29,624] [INFO] [launch.py:246:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2023-04-16 18:06:29,624] [INFO] [launch.py:247:main] dist_world_size=4
[2023-04-16 18:06:29,624] [INFO] [launch.py:249:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
Traceback (most recent call last):
  File "/home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb", line 499, in <module>
Traceback (most recent call last):
  File "/home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb", line 499, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
    "execution_count": null,
NameError: name 'null' is not defined
Traceback (most recent call last):
  File "/home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb", line 499, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
Traceback (most recent call last):
  File "/home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb", line 499, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2023-04-16 18:06:30,638] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 122671
[2023-04-16 18:06:30,654] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 122672
[2023-04-16 18:06:30,654] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 122673
[2023-04-16 18:06:30,667] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 122674
[2023-04-16 18:06:30,681] [ERROR] [launch.py:434:sigkill_handler] ['/home/stsingha/anaconda3/envs/openchatkit_fastapi/bin/python', '-u', '/home/stsingha/LLM/dolly_new/dolly/training/train_dolly_new.ipynb', '--local_rank=3', '--deepspeed', '--deepspeed_config', '/home/stsingha/LLM/dolly/training/deepspeedconfig.json'] exits with return code = 1

**Comment by srowen** [comment]
On what hardware? this almost always means OOM. You need a big machine for fine tuning, and I see a lot of people trying this on hardware that's far too small. You're not even saying here what model you're working with.

**Comment by singhalshikha518** [comment]
I am fine tuning EleutherAI/pythia-2.8b on 4 A10 machine.

(base) bash-4.2$ nvidia-smi
Sun Apr 16 19:27:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          Off  | 00000000:17:00.0 Off |                    0 |
|  0%   31C    P8    15W / 150W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A10          Off  | 00000000:31:00.0 Off |                    0 |
|  0%   32C    P8    17W / 150W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A10          Off  | 00000000:B1:00.0 Off |                    0 |
|  0%   33C    P8    17W / 150W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A10          Off  | 00000000:CA:00.0 Off |                    0 |
|  0%   32C    P8    18W / 150W |      0MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
<img width="607" alt="Screenshot 2023-04-17 at 1 07 51 AM" src="https://user-images.githubusercontent.com/30156021/232337841-27e80e49-d529-475a-9009-c94401518cab.png">

**Comment by singhalshikha518** [comment]
> On what hardware? this almost always means OOM. You need a big machine for fine tuning, and I see a lot of people trying this on hardware that's far too small. You're not even saying here what model you're working with.

I am fine tuning EleutherAI/pythia-2.8b on 4 A10 machine.

(base) bash-4.2$ nvidia-smi
Sun Apr 16 19:27:50 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03 Driver Version: 470.141.03 CUDA Version: 11.4 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 NVIDIA A10 Off | 00000000:17:00.0 Off | 0 |
| 0% 31C P8 15W / 150W | 0MiB / 22731MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
| 1 NVIDIA A10 Off | 00000000:31:00.0 Off | 0 |
| 0% 32C P8 17W / 150W | 0MiB / 22731MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
| 2 NVIDIA A10 Off | 00000000:B1:00.0 Off | 0 |
| 0% 33C P8 17W / 150W | 0MiB / 22731MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
| 3 NVIDIA A10 Off | 00000000:CA:00.0 Off | 0 |
| 0% 32C P8 18W / 150W | 0MiB / 22731MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
Screenshot 2023-04-17 at 1 07 51 AM

**Comment by srowen** [comment]
This works fine for me for the 2.8B model on 4 x A10 (g5.24xlarge) if I change the batch size to 2. I'm working on guidance for tuning this on machines besides the A100.

**Comment by singhalshikha518** [comment]
I tried Fine Tuning 2.8B model on 4 x A10. Based on the instructions given if i add "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    under zero_optimization i am getting below error. And when i am not adding this i am getting Cuda Out of memory error

Below are my error logs:
File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 328, in __init__
    engine = DeepSpeedEngine(args=args,    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 574, in _create_fp16_partitions_with_defragmentation
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_optimizer
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_optimizer

  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 328, in __init__
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 410, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1465, in _configure_zero_optimizer
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1187, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1465, in _configure_zero_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1465, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    optimizer = DeepSpeedZeroOptimizer_Stage3(    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 574, in _create_fp16_partitions_with_defragmentation

  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    device_buffer = __class__.defragment(parameter_partitions)    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 574, in _create_fp16_partitions_with_defragmentation

  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 410, in defragment
    device_buffer = __class__.defragment(parameter_partitions)    assert len(set(t.device for t in tensors)) == 1
AssertionError

  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 410, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation(self.trainable_param_groups)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 574, in _create_fp16_partitions_with_defragmentation
    device_buffer = __class__.defragment(parameter_partitions)
  File "/home/stsingha/anaconda3/envs/openchatkit_fastapi/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 410, in defragment
    assert len(set(t.device for t in tensors)) == 1
AssertionError
[2023-04-17 11:47:26,474] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 48561
[2023-04-17 11:47:26,475] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 48562
[2023-04-17 11:47:26,709] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 48563
[2023-04-17 11:47:26,731] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 48564
[2023-04-17 11:47:27,125] [ERROR] [launch.py:434:sigkill_handler] ['/home/stsingha/anaconda3/envs/openchatkit_fastapi/bin/python', '-u', '-m', 'training.trainer', '--local_rank=3', '--deepspeed', '/home/stsingha/LLM/dolly_finetuning/dolly/config/ds_z3_bf16_config.json', '--epochs=1', '--local-output-dir=/home/stsingha/LLM/dolly_finetuning/dolly/dolly3b', '--per-device-train-batch-size=2', '--per-device-eval-batch-size=2', '--lr=1e-5'] exits with return code = 1

**Comment by singhalshikha518** [comment]
Any idea on below error:
site-packages/deepspeed/runtime/zero/stage3.py", line 410, in defragment
assert len(set(t.device for t in tensors)) == 1
AssertionError

**Comment by singhalshikha518** [comment]
I am using this repo and following all the steps mentioned here:
https://github.com/youkaichao/dolly#train-the-model

**Comment by srowen** [comment]
On what hardware? this worked for me last night on a g5.24xlarge. Are you sure there are no other differences? the 2.8B model right?

**Comment by singhalshikha518** [comment]
2.8 model is working for me now. Just wanted to check can we fine tune 7B model with the same configuration?

**Comment by srowen** [comment]
Yes, again see the README in the repo. You need a different change to config, but it will work on A10s. Deepspeed param offload is the key, instead of changing batch size

**Comment by singhalshikha518** [comment]
In deep speed config if we use:
"zero_optimization": {
    "stage": 2,
	  "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
	  "allgather_partitions": true,
	  "allgather_bucket_size": 5e8,
	  "contiguous_gradients": true
  },
  
  Will there be any difference in model performance?

**Comment by singhalshikha518** [comment]
With Stage 3 i was getting Assertion Error. When i changed it to Stage 2 it was running fine

**Comment by srowen** [comment]
It won't work with stage 2. Leave the settings as is and make only the recommended modification. That worked for me on 4 x 10 and the 7B model even

**Comment by singhalshikha518** [comment]
I am getting Cuda out of memory error. Also, When I am trying with multiple nodes. Training got stuck at:
[torch.distributed.distributed_c10d] Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:1 (world_size=8, worker_count=6, timeout=0:30:00)

I am having 2 clusters with 4A10 Gpus in each cluster.
Anything that i need to change for 2 nodes.

**Comment by srowen** [comment]
This uses 1 machine, not a cluster. You'd have to say more about your modifications; it doesn't seem like you're running this with the out-of-the-box instructions.
